#   version 1.4.2
#
# Port that the Webserver is accessible to
WEBSERVER_PORT: 5000

# Path to Caddy file
CADDYFILE_PATH: "/etc/caddy/Caddyfile"

# Multiple available base domain choices for your web dashboard dropdown
DOMAINS:
  - "change.me"
  - "change.me1"

# The ip of your DNS Rewrite server
ADGUARD_IP: "192.168.1.59"